### ISSUE TITLE
Column lineage fails with `Failed to parse '<fully qualified model name>' into <class 'sqlglot.expressions.Table'>`

### ISSUE THREAD

**Issue by plaflamme** [TobikoData/sqlmesh#2016] opened 2024-01-24 18:53 UTC
The slightly edited traceback:

```
Traceback (most recent call last):
  File ".venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1064, in parse_into
    return self._parse(parser, raw_tokens, sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1103, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File ".venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1144, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 4.
  abc-defghi-jklmnop-qr.abcdefg__hij.ab_cde_fghijklmn

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File ".venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File ".venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File ".venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File ".venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File ".venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File ".venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File ".venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File ".venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File ".venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/web/server/api/endpoints/lineage.py", line 87, in column_lineage
    models=_process_downstream(node.downstream),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/web/server/api/endpoints/lineage.py", line 41, in _process_downstream
    table = _get_table(node)
            ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/web/server/api/endpoints/lineage.py", line 24, in _get_table
    return exp.table_name(table, identify=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 6671, in table_name
    table = maybe_parse(table, into=Table, dialect=dialect)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/expressions.py", line 5521, in maybe_parse
    return sqlglot.parse_one(sql, read=dialect, into=into, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/__init__.py", line 123, in parse_one
    result = dialect.parse_into(into, sql, **opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/dialects/dialect.py", line 447, in parse_into
    return self.parser(**opts).parse_into(expression_type, self.tokenize(sql), sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/sqlglot/parser.py", line 1069, in parse_into
    raise ParseError(
sqlglot.errors.ParseError: Failed to parse 'abc-defghi-jklmnop-qr.abcdefg__hij.ab_cde_fghijklmn' into <class 'sqlglot.expressions.Table'>
```

The schemata names were changed from their original name to `abcde...` but keeping dashes and underscores at the same place.

Here's a screenshot of the error in the ui itself

<img width="1230" alt="Screenshot 2024-01-23 at 13 25 52" src="https://github.com/TobikoData/sqlmesh/assets/484152/56995447-09b3-4fe0-9ae5-a65b8b036106">

**Comment by tobymao** [comment] 2024-02-07 03:07
@vchan has this been addressed?

**Comment by georgesittas** [comment] 2024-02-16 23:54
Hey @plaflamme can you share a reproduction sequence for this?

**Comment by vchan** [comment] 2024-02-17 00:03
This may be fixed in my #2059. I am finalizing a few things with regards to unions in queries for lineage and hope to finish the PR soon.

**Comment by georgesittas** [comment] 2024-02-17 00:12
Cool, just asking to double-check if this is still an issue because I was playing around with the lineage and couldn't repro after trying a couple of things.

**Comment by georgesittas** [comment] 2024-02-17 00:25
After investigating a bit it seems like this may have been an issue in an older version, as the error message shows an outdated implementation of `_get_table` in lineage.py:

```python
  File ".venv/lib/python3.11/site-packages/web/server/api/endpoints/lineage.py", line 24, in _get_table
    return exp.table_name(table, identify=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This seems fixed in the latest main: https://github.com/TobikoData/sqlmesh/blob/17deccd7190d62785453a60cd7aaef06cec4d5a4/web/server/api/endpoints/lineage.py#L32

With the dialect being propagated to `table_name`, my expectation is that there shouldn't be a parsing issue anymore. Gonna close this one for now, but if the issue persists I'll repon and we'll investigate it further @plaflamme.

**Closed by georgesittas** 2024-02-17 00:25 UTC
Labels: Bug

**Comment by yshalaby-ft** [comment] 2024-05-16 01:44
Hello, I've recently encountered this same issue in the UI. I've been able to isolate it to a single CTE within one of my models that uses a UNION. When I remove the UNION and define the CTE as a simple select, the issue goes away. I am using version 0.95.1.
Here is a minimal example:
```sql
WITH cte1 AS (
  SELECT
    from_name,
    to_name,
    card_id,
    eventtime
  FROM upstream.table
), stacked AS (
  SELECT
    from_name AS phase,
    card_id,
    NULL::TIMESTAMP AS entered_phase_at
  FROM phase_moves_raw
  WHERE
    1 = 1
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY card_id ORDER BY eventtime) = 1
  UNION
  SELECT
    to_name AS phase,
    card_id,
    eventtime AS entered_phase_at
  FROM phase_moves_raw
), 
SELECT
  phase,
  card_id,
  entered_phase_at,
  LEAD(entered_phase_at) OVER (PARTITION BY card_id ORDER BY entered_phase_at NULLS FIRST) AS exit_phase_at
FROM phase_moves_raw
```

This issue hasnt prevented me from runing plan or apply, it just appears in the UI when I attempt trace column level lineage for "entered_phase_at" and "exit_phase_at" columns.

**Comment by tobymao** [comment] 2024-05-16 01:51
@yshalaby-ft where is dev.schema.tablename coming from?

**Comment by yshalaby-ft** [comment] 2024-05-16 01:52
That's just me anonymizing the name of the model. Would it be helpful for me to share the actual name?

**Comment by tobymao** [comment] 2024-05-16 03:08
cc @vchan

**Comment by tobymao** [comment] 2024-05-16 18:47
https://github.com/TobikoData/sqlmesh/pull/2622#pullrequestreview-2061632332

**Comment by vchan** [comment] 2024-05-16 18:57
This should be fixed now.
