### ISSUE TITLE
sqlmesh format unstable with multi-line description

### ISSUE THREAD

**Issue by simon-pactum** [TobikoData/sqlmesh#3456] opened 2024-12-03 13:31 UTC
```
MODEL (
  name sqlmesh_example.multiline,
  description "first line
    second line"
);

SELECT
  1
```

When running `sqlmesh format` each successive run will push the second line further to the right by two spaces each run.

I tried to work around it with:

```
-- first line
-- second line
MODEL ( ...
```

Which while stable, gets unreadable pretty fast as it converts to:

```
/* first line */ /* second line */
MODEL ( ...
```

But at least I can manually make one big:

```
/*
first line
second line
*/
```

Which works as expected

sqlmesh version: 0.137.1
dialect: postgres

**Comment by georgesittas** [comment] 2024-12-03 13:37
Interesting, thanks for the report. I can reproduce this:

> each successive run will push the second line further to the right by two spaces each run.

Will take a look.

**Comment by georgesittas** [comment] 2024-12-03 13:45
Actually, @simon-pactum I think the problem is that you used double quotes (`"`) instead of single quotes (`'`). The latter works fine, the former is used to specify identifiers (e.g., column names). I'll go ahead and close this issue, but happy to continue discussign and/or reopen if needed.

**Closed by georgesittas** 2024-12-03 13:45 UTC

**Comment by simon-pactum** [comment] 2024-12-03 13:55
Oh! Good spot, thanks!
