### ISSUE TITLE
Outdated tutorial docs? Adding column breaks tests

### ISSUE THREAD

**Issue by schlich** [TobikoData/sqlmesh#1452] opened 2023-09-20 17:49 UTC
Hello, I'm working through the introduction tutorial and running `sql plan dev` in the tutorial causes an error due to a broken test:

```
----------------------------------------------------------------------
Test Failure Summary
======================================================================
Num Successful Tests: 0
Failure Test: sqlmesh_example.full_model test_example_full_model
======================================================================
E
======================================================================
ERROR: test_example_full_model (C:\Users\tcschlic\csi-sqlmesh\tests\test_full_model.yaml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tcschlic\csi-sqlmesh\.venv\Lib\site-packages\sqlmesh\core\test\definition.py", line 82, in setUp
    self.engine_adapter.create_view(_test_fixture_name(table_name), df, columns_to_types)
  File "C:\Users\tcschlic\csi-sqlmesh\.venv\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 616, in create_view
    self.execute(
  File "C:\Users\tcschlic\csi-sqlmesh\.venv\Lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 1238, in execute
    self.cursor.execute(sql, **kwargs)
duckdb.BinderException: Binder Error: table "t" has 3 columns available but 4 columns specified

----------------------------------------------------------------------
Ran 1 test in 0.026s

FAILED (errors=1)

Error: Cannot generate plan due to failing test(s). Fix test(s) and run again
```

Seems like intended behavior, just not documented, so I thought I'd flag

**Comment by izeigerman** [comment] 2023-09-20 18:18
Looks like a gap in the documentation indeed. Thanks for reporting this, @schlich!

CC: @treysp

**Comment by abbywake** [comment] 2023-09-20 18:36
Just came across the same error!

**Comment by izeigerman** [comment] 2023-09-20 21:33
It appears that we indeed had a regression which has been addressed in `0.32.2`. Closing this now

**Closed by izeigerman** 2023-09-20 21:33 UTC
Labels: Documentation

**Comment by abbywake** [comment] 2023-09-21 21:11
@izeigerman I am still getting the same error

**Comment by tobymao** [comment] 2023-09-21 21:13
@abbywake did you upgrade sqlmesh?

**Comment by abbywake** [comment] 2023-09-21 21:18
@tobymao What do I run to upgrade?

**Comment by abbywake** [comment] 2023-09-21 21:22
Got it. Thanks!

**Comment by tobymao** [comment] 2023-09-21 21:33
@abbywake can you confirm that it works now?
